INSERT INTO EMPLE (EMPNO, NOMBRE, OFICIO, MGR, FECALTA, SAL, COMM, DEPT_NO) 
VALUES(((SELECT MAX(EMPNO) FROM EMPLE) + 1), 'PEPE', 'vendedor', 7698, SYSDATE, 1700, 100, 30);

SELECT * FROM EMPLE WHERE EMPNO = 7936;
